{% set version = "v1.0.0" %}

package:
  name: omero-importer-cli
  version: {{ version }}

source:
  url: https://github.com/qbicsoftware/omero-importer-cli/releases/download/OMERO-5.4.6-ice36-b87-v1.0.0/omero-importer.jar

build:
  noarch: generic
  number: 0

requirements:
  run:
    - openjdk
    - python

test:
  commands:
    - omero-importer -h  >/dev/null
